name: Release

on:
  workflow_dispatch:
  push:
    tags: '*'

jobs:

  Build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-x64
          - os: ubuntu-latest
            platform: linux-musl-x64
          - os: windows-latest
            platform: win-x64
          - os: windows-latest
            platform: win-arm64
          - os: macos-latest
            platform: osx-x64
          - os: macos-latest
            platform: osx-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Publish
        run: dotnet publish -r ${{ matrix.platform }} --self-contained

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: 'src/ReportPortal.GaugePlugin/bin/Release/net8.0/${{matrix.platform}}/*.zip'
          compression-level: 0

  Release:
    environment:
      name: GitHub Releases
      url: https://github.com/reportportal/agent-net-gauge/releases
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
      - name: Create GitHub Release
        run: gh release create ${{ github.ref_name }} ./**/*.zip --generate-notes --draft --repo reportportal/agent-net-gauge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}